---
# tasks file for ipr.ansible.xymon

- name: Load specific OS vars for xymon
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

# client {{{
- name: client package
  package:
    name: '{{ item }}'
    state: '{{ xymon_cli_pkg_state }}'
  with_items:
    - '{{ xymon_cli_pkg_list }}'
  when: xymon_cli_manage

- name: CONFIG xymon-client service
  template:
    src: '{{ xymon_cli_default_conf_tpl }}'
    dest: '{{ xymon_cli_default_conf_path }}'
    owner:  root
    group:  root
    mode:   0644
    backup: true
  when: xymon_cli_manage
  notify: restart xymon-client service

- name: CONFIG xymon user's groups
  user:
    name: xymon
    groups: '{{ xymon_user_groups }}'
  notify: restart xymon-client service

## service
- name: SERVICE manage '{{ xymon_cli_service_name }}'
  service:
    name: '{{ xymon_cli_service_name }}'
    state: started
    enabled: '{{ xymon_cli_service_enabled }}'
  when: xymon_cli_service_manage
# }}}

# plugins {{{
- name: PLUGIN mq packages
  package:
    name: '{{ item }}'
    state: '{{ "present" if xymon_plug_mq_state else "absent" }}'
  with_items:
    - '{{ xymon_plug_mq_package }}'
  when: xymon_plug_manage
  notify: restart xymon-client service

- name: PLUGIN mq
  template:
    src: '{{ xymon_plug_mq_tpl }}'
    dest: '{{ xymon_plug_mq_path }}'
    owner:  root
    group:  root
    mode:   0644
  when: xymon_plug_manage
  notify: restart xymon-client service

- name: PLUGIN libs packages
  package:
    name: '{{ item }}'
    state: '{{ "present" if xymon_plug_libs_state else "absent" }}'
  with_items:
    - '{{ xymon_plug_libs_package }}'
  when: xymon_plug_manage
  notify: restart xymon-client service

- name: PLUGIN libs
  template:
    src: '{{ xymon_plug_libs_tpl }}'
    dest: '{{ xymon_plug_libs_path }}'
    owner:  root
    group:  root
    mode:   0644
  when: xymon_plug_manage
  notify: restart xymon-client service
# }}}
