---
# tasks file for ipr.ansible.xymon

- name: Load specific OS vars for xymon
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

# client {{{
- name: client package
  package:
    name: '{{ item }}'
    state: '{{ xymon_cli_pkg_state }}'
  with_items:
    - '{{ xymon_cli_pkg_list }}'
  when: xymon_cli_manage

## service
- name: SERVICE manage '{{ xymon_cli_service_name }}'
  service:
    name: '{{ xymon_cli_service_name }}'
    state: started
    enabled: '{{ xymon_cli_service_enabled }}'
  when: xymon_cli_service_manage
# }}}
