---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker
#
# tasks file for ipr.ansible.xymon

- name: Load specific OS vars for xymon
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

# Manage required client packages [[[1
- name: client package
  package:
    name: '{{ xymon_cli__pkg_list | flatten }}'
    state: '{{ xymon_cli__pkg_state }}'
  register: cli_result
  until: cli_result is success
  when: xymon_cli__manage|bool

# Manage client configuration [[[1
- name: CONFIG xymon-client service
  template:
    src: '{{ xymon_cli__default_conf_tpl }}'
    dest: '{{ xymon_cli__default_conf_path }}'
    owner: root
    group: root
    mode: 0644
    backup: true
  when: xymon_cli__manage|bool
  notify: restart xymon-client service

- name: CONFIG xymon user's groups
  user:
    name: xymon
    groups: '{{ xymon_cli__user_groups }}'
    append: true
  when: xymon_cli__manage|bool
  notify: restart xymon-client service

# Manage service [[[1
- name: SERVICE manage '{{ xymon_cli__service_name }}'
  service:
    name: '{{ xymon_cli__service_name }}'
    state: started
    enabled: '{{ xymon_cli__service_enabled }}'
  when: (xymon_cli__manage|bool and
         xymon_cli__service_manage|bool)

# Manage all plugins's packages [[[1
- name: PLUGINS package and dependencies
  package:
    name: '{{ xymon_cli__plug_combined_packages | flatten }}'
    state: 'present'
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool)
  register: combined_packages_plug_result
  until: combined_packages_plug_result is success
  notify: restart xymon-client service

# Manage plugins clientlaunch files [[[1
- name: PLUGINS clientlaunch files
  template:
    src: '{{ item.template }}'
    dest: '{{ item.path }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - '{{ xymon_cli__plug_combined_clientlaunch }}'
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool)
  notify: restart xymon-client service

# Manage apt plugin [[[1
- name: PLUGIN apt no_repo_accept whitelist
  template:
    src: 'etc/xymon/apt_no_repo_accept.j2'
    dest: '/etc/xymon/apt_no_repo_accept'
    owner: root
    group: root
    mode: 0644
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool)
  notify: restart xymon-client service

# Manage libs plugin [[[1
- name: PLUGIN libs whitelist
  template:
    src: 'etc/xymon/libs.local.yaml.j2'
    dest: '/etc/xymon/libs.local.yaml'
    owner: root
    group: root
    mode: 0644
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool)
  notify: restart xymon-client service

# Manage net plugin [[[1
- name: PLUGIN net config template
  template:
    src: '{{ xymon_cli__plug_net_conf_tpl }}'
    dest: '{{ xymon_cli__plug_net_conf_path }}'
    owner: root
    group: root
    mode: 0644
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool)
  notify: restart xymon-client service

# Manage sge plugin [[[1
- name: PLUGIN sge script file from template
  template:
    src: '{{ xymon_cli__plug_sge_script_tpl }}'
    dest: '{{ xymon_cli__plug_sge_script_path }}'
    owner: root
    group: xymon
    mode: 0755
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool and
         xymon_cli__plug_sge_script_url|length == 0 )
  notify: restart xymon-client service

- name: PLUGIN sge script file from URL
  get_url:
    url:   '{{ xymon_cli__plug_sge_script_url }}'
    dest:  '{{ xymon_cli__plug_sge_script_path }}'
    owner: root
    group: xymon
    mode:  0755
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool and
         xymon_cli__plug_sge_script_url|length > 0 )
  notify: restart xymon-client service

# Manage smartoverall plugin [[[1
- name: PLUGIN smartoverall script file from template
  template:
    src: '{{ xymon_cli__plug_smartoverall_script_tpl }}'
    dest: '{{ xymon_cli__plug_smartoverall_script_path }}'
    owner: root
    group: xymon
    mode: 0755
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool and
         xymon_cli__plug_smartoverall_script_url|length == 0 )
  notify: restart xymon-client service

- name: PLUGIN smartoverall script file from URL
  get_url:
    url:   '{{ xymon_cli__plug_smartoverall_script_url }}'
    dest:  '{{ xymon_cli__plug_smartoverall_script_path }}'
    owner: root
    group: xymon
    mode:  0755
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool and
         xymon_cli__plug_smartoverall_script_url|length > 0 )
  notify: restart xymon-client service

# Manage smart plugin [[[1
- name: PLUGIN smart script file from template
  template:
    src: '{{ xymon_cli__plug_smart_script_tpl }}'
    dest: '{{ xymon_cli__plug_smart_script_path }}'
    owner: root
    group: xymon
    mode: 0755
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool and
         xymon_cli__plug_smart_script_url|length == 0 )
  notify: restart xymon-client service

- name: PLUGIN smart script file from URL
  get_url:
    url:   '{{ xymon_cli__plug_smart_script_url }}'
    dest:  '{{ xymon_cli__plug_smart_script_path }}'
    owner: root
    group: xymon
    mode:  0755
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool and
         xymon_cli__plug_smart_script_url|length > 0 )
  notify: restart xymon-client service

# Manage zfs plugin [[[1
- name: PLUGIN zfs script file
  template:
    src: '{{ xymon_cli__plug_zfs_script_tpl }}'
    dest: '{{ xymon_cli__plug_zfs_script_path }}'
    owner: root
    group: xymon
    mode: 0755
  when: (xymon_cli__manage|bool and
         xymon_cli__plug_manage|bool)
  notify: restart xymon-client service
